spring:  
  profiles: 
    active: 
    - dev 
spring: 
   profiles: dev 
   application:
     name: study-springcloud-dept-atguigu-dev
spring:    
   profiles: test 
   application: 
     name: study-springcloud-dept-atguigu-test